import { ListFormat } from '@prisma/client';

export type BrazilListSeedRoster = {
  position: number;
  name: string;
  nickname?: string;
  carNumber?: string;
  car?: string;
  team?: string;
  isKing?: boolean;
  vacancy?: boolean;
};

export type BrazilListSeed = {
  areaCode: number;
  name: string;
  format: ListFormat;
  administratorName?: string;
  hometown?: string;
  active: boolean;
  roster: BrazilListSeedRoster[];
};

export const BRAZIL_LISTS: BrazilListSeed[] = [
  {
    areaCode: 12,
    name: 'Lista Área 12',
    format: ListFormat.TOP_10,
    active: true,
    roster: [
      { position: 1, name: 'Erick Filipini', team: 'Arrancavale' },
      { position: 2, name: 'Andrio Ferreira', team: 'Doria Garage' },
      { position: 3, name: 'Breno Ribeiro', team: 'WS' },
      { position: 4, name: 'Silvano Junior', team: 'Bob Motorsport' },
      { position: 5, name: 'Rona Ronaldo', team: 'Pescoço' },
      { position: 6, name: 'Igor Fernandes', team: 'Boosted Race Team' },
      { position: 7, name: 'Peterson Almeida', team: 'Bob Motorsport' },
      { position: 8, name: 'Raphael Chagas', team: 'Galo / Cabeça' },
      { position: 9, name: 'João Biaggi', team: 'Perfectcar Racing' },
      { position: 10, name: 'Felipe Monstrinho', team: 'Arrancavale' },
    ],
  },
  {
    areaCode: 15,
    name: 'Lista Área 15',
    format: ListFormat.TOP_20,
    administratorName: 'Tilico Carnelos',
    active: true,
    roster: [
      { position: 1, name: 'Diego', isKing: true, car: 'Gol FLD', team: "D'Paula Racing" },
      { position: 2, name: 'Chiquinho', car: 'Gol 4x4', team: 'DG Motorsport' },
      { position: 3, name: 'Motoca', car: 'Chevette', team: 'SZM Racing' },
      { position: 4, name: 'Samuka', car: 'Chevy', team: 'Volt Performance' },
      { position: 5, name: 'Barba', car: 'Passat 4x4', team: 'Mecânica Barba' },
      { position: 6, name: 'Montanaro', car: 'Gol 4x4', team: 'Kiwi Motorsport' },
      { position: 7, name: 'Felipe', car: 'Fiat 147', team: 'MZ Motorsport' },
      { position: 8, name: 'Texeira', car: 'Kadett', team: 'Texeira Car' },
      { position: 9, name: 'Hulkinho', car: 'Gol', team: 'MZ Motorsport' },
      { position: 10, name: 'Ricardo', car: 'Gol 4x4', team: 'GP Cabeçotes' },
      { position: 11, name: 'Shimanuki', car: 'Gol 4x4', team: 'Perfectcar' },
      { position: 12, name: 'Vagner', car: 'Santana', team: 'Perfectcar' },
      { position: 13, name: 'Netto', car: 'Gol FLD', team: 'Kiwi Motorsport' },
      { position: 14, name: 'Pakuera', car: 'Passat FLD', team: 'Sport Preparações' },
      { position: 15, name: 'Augusto', car: 'Gol 4x4', team: 'Perfectcar' },
      { position: 16, name: 'Juninho', car: 'Chevette', team: 'DG Motorsport' },
      { position: 17, name: 'Claitinho', car: 'Gol 4x4', team: 'Perfectcar' },
      { position: 18, name: 'Daniele', car: 'Voyage', team: 'SZM Electric' },
      { position: 19, name: 'Marcelo', car: 'Gol', team: 'SZM Electric' },
      { position: 20, name: 'Henrique', car: 'Chevette', team: 'DG Motorsport' },
    ],
  },
  {
    areaCode: 16,
    name: 'Lista Área 16',
    format: ListFormat.TOP_10,
    administratorName: 'Robson Boi',
    active: true,
    roster: [
      { position: 1, name: 'Kauahn', car: 'Gol 4x4', team: 'G.R. Motorsport' },
      { position: 2, name: 'Tiago', car: 'Gol 4x4', team: 'Kiwi Motorsport' },
      { position: 3, name: 'Klios', car: 'Gol 4x4', team: 'G.R. Motorsport' },
      { position: 4, name: 'Rodrigo', car: 'Chevette', team: 'Kiwi Motorsport' },
      { position: 5, name: 'Arroiz', car: 'Gol 4x4', team: 'Kiwi Motorsport' },
      { position: 6, name: 'Lucas', car: 'Gol FLD', team: 'Race Car' },
      { position: 7, name: 'Thatiane Lopes', car: 'Gol 4x4', team: 'Brothers Motorsport' },
      { position: 8, name: 'Adriano', car: 'Gol', team: 'Sudatts Motorsports' },
      { position: 9, name: 'Horse', car: 'Gol 4x4', team: 'Madinho Drag Team' },
      { position: 10, name: 'Igor', car: 'Gol 4x4', team: 'Kiwi Motorsport' },
    ],
  },
  {
    areaCode: 18,
    name: 'Lista Área 18',
    format: ListFormat.TOP_20,
    administratorName: 'Adré Kareca',
    active: true,
    roster: [
      { position: 1, name: 'Troiano', carNumber: '511', car: 'Gol Metal FLD', team: 'Total Flex' },
      { position: 2, name: 'Wendel', carNumber: '121', car: 'Gol Killer FLD', team: 'Total Flex' },
      { position: 3, name: 'Juliano', carNumber: '700', car: 'Gol Aspirado Nitro', team: 'Zidoro Motorsport' },
      { position: 4, name: 'Bic', carNumber: '69', car: 'Gol 4x4', team: 'Cacá / Dragster' },
      { position: 5, name: 'Nandão', carNumber: '180', car: 'Gol D. Turbo', team: 'SX Racing' },
      { position: 6, name: 'Kareka', carNumber: '77', car: 'Gol 4x4', team: '77 - Cacá' },
      { position: 7, name: 'Kapacete', carNumber: '115', car: 'Gol FLD', team: 'Kapacete Motorsports' },
      { position: 8, name: 'Fabiano', carNumber: '2200', car: 'Fusca AP Turbo', team: 'Endurance' },
      { position: 9, name: 'Igor', carNumber: '18', car: 'Amarok V6', team: 'CKC Performance' },
      { position: 10, name: 'Leandro Goes', carNumber: '901', car: 'Fusca Turbo', team: 'Reche Preparações' },
      { position: 11, name: 'Tedy Jr', carNumber: '2781', car: 'Gol 4x4', team: 'A1 Automecânica' },
      { position: 12, name: 'Tuim', carNumber: '89', car: 'Voyage FLD', team: 'Kapacete Motorsports' },
      { position: 13, name: 'Tiago 18', car: 'Voyage D. Turbo', team: 'DL Automecanica' },
      { position: 14, name: 'Julia Montalli', carNumber: '222', car: 'Up Turbo', team: 'Auto Montalli' },
      { position: 15, name: 'Geraldo', carNumber: '2500', car: 'Dodge Ram 4x4', team: 'Flow Boost' },
      { position: 16, name: 'Rayner', carNumber: '224', car: 'Gol 4x4', team: 'Kapacete Motorsports' },
      { position: 17, name: 'Uilian', carNumber: '87', car: 'Marajó FLT', team: 'Febrento Motorsport' },
      { position: 18, vacancy: true, name: 'Vaga 18 / Área 18' },
      { position: 19, vacancy: true, name: 'Vaga 19 / Área 18' },
      { position: 20, vacancy: true, name: 'Vaga 20 / Área 18' },
    ],
  },
  {
    areaCode: 21,
    name: 'Lista Área 21',
    format: ListFormat.TOP_10,
    active: true,
    roster: [
      { position: 1, name: 'Paulino', car: 'Gol 4x4' },
      { position: 2, name: 'Jackson', car: 'Gol Sonic' },
      { position: 3, name: 'Boiadeiro', car: 'Gol' },
      { position: 4, name: 'Presuntinho', car: 'Opala' },
      { position: 5, name: 'Translemos', car: 'Gol 4x4 / Justiceiro' },
      { position: 6, name: 'Pork', car: 'Chevette Fantasma' },
      { position: 7, name: 'Daniel', car: 'Gol' },
      { position: 8, name: 'Bacurau', car: 'Gol FLD' },
      { position: 9, name: 'Walber', car: 'Gol' },
      { position: 10, name: 'Rocket', car: 'Gol' },
    ],
  },
  {
    areaCode: 31,
    name: 'Lista Área 31',
    format: ListFormat.TOP_10,
    administratorName: 'David Guitti',
    active: true,
    roster: [
      { position: 1, name: 'Cecotti' },
      { position: 2, name: 'Evaldo' },
      { position: 3, name: 'Tomback' },
      { position: 4, name: 'Rytchelle' },
      { position: 5, name: 'Piccolino' },
      { position: 6, name: 'Du Absolut' },
      { position: 7, name: 'Kadu' },
      { position: 8, name: 'Castanon' },
      { position: 9, name: 'Bruno Fabri' },
      { position: 10, name: 'Bruna Mussarela' },
    ],
  },
  {
    areaCode: 43,
    name: 'Lista Área 43',
    format: ListFormat.TOP_20,
    administratorName: 'Cadu Moreira',
    active: true,
    roster: [
      { position: 1, name: 'Calegare', car: 'Gol 4x4 Minion', team: 'Batistella Motores' },
      { position: 2, name: 'Malassise', car: 'Saveiro 4x4 Hulk', team: 'Dragster Motorsport' },
      { position: 3, name: 'Chavinsky', car: 'Gol 4x4 217', team: 'Dragster Motorsport' },
      { position: 4, name: 'Brunini', car: 'Gol FLD Laranja', team: 'Grillo Motorsport' },
      { position: 5, name: 'Piruka', car: 'Gol 4x4 Cinza', team: 'Ferrari Motorsport' },
      { position: 6, name: 'Fábio Marques', car: 'Audi RS3', team: 'Atomic Motorsport' },
      { position: 7, name: 'Igor Silvestre', car: 'Gol 4x4 Prata', team: 'Aliança Motorsport' },
      { position: 8, name: 'Gleocar', car: 'Gol G3 4x4', team: 'Mecânica Gleocar' },
      { position: 9, name: 'Faustino', car: 'Gol 4x4 Black', team: 'Cabos Motorsport' },
      { position: 10, name: 'Hudema', car: 'Opala Carbon', team: 'Equipe 100 Gas' },
      { position: 11, name: 'Malcon', car: 'Corsa Turbo', team: 'Cabos Motorsport' },
      { position: 12, name: 'Vinícius', car: 'Chevette', team: 'Aliança Motorsport' },
      { position: 13, name: 'Nilo Caio', car: 'Tático Cinza', team: 'Aliança Motorsport' },
      { position: 14, name: 'Anderson 43', car: 'Gol Bola', team: 'Ferrari Motorsport' },
      { position: 15, name: 'Ana Paula', car: 'Gol Maravilha', team: 'Teruo Motorsport' },
      { position: 16, name: 'Titi', car: 'Gol 4x4 Zumbi', team: 'Cargados Racing' },
      { position: 17, name: 'Flávio', car: 'Porsche 911 Turbo S', team: 'Atomic Motorsport' },
      { position: 18, name: 'Leo Torkim', car: 'Voyage Torkim', team: 'Teruo Motorsport' },
      { position: 19, name: 'Robson', car: 'Gol 4x4', team: 'Aliança Motorsport' },
      { position: 20, name: 'Carlos', car: 'Gol G3 4x4', team: 'Cabos Motorsport' },
    ],
  },
  {
    areaCode: 44,
    name: 'Lista Área 44',
    format: ListFormat.TOP_20,
    administratorName: 'Junior Vecinho',
    active: true,
    roster: [
      { position: 1, name: 'Catarina', team: 'Catarina / Adriturbo' },
      { position: 2, name: 'Dino', team: 'Dino Race & Adriturbo' },
      { position: 3, name: 'Bastião', team: 'Mec. J.A Adriturbo' },
      { position: 4, name: 'Diegão', team: 'Injetec' },
      { position: 5, name: 'Maykon', team: 'Injetec' },
      { position: 6, name: 'Nardin', team: 'Armada Wataya' },
      { position: 7, name: 'Pety', team: 'Injetec' },
      { position: 8, name: 'Doceiro', team: 'Rápidos Drag Race' },
      { position: 9, name: 'Dittin', team: 'Dittin Motorsport' },
      { position: 10, name: 'Vitor', team: 'Papke Motorsport' },
      { position: 11, name: 'Sanga', team: 'Sanga Motorsports' },
      { position: 12, name: 'Robinho', team: 'Cabos Motorsport' },
      { position: 13, name: 'André', team: 'Explosão Adriturbo' },
      { position: 14, name: 'Carlão', team: 'Tissei Motorsport' },
      { position: 15, name: 'Toru', team: 'Tissei Motorsport' },
      { position: 16, name: 'Gildo', team: 'Rápidos Drag R.' },
      { position: 17, name: 'Hugo', team: 'Star Racing' },
      { position: 18, name: 'Caio', team: 'Tissei Motorsport' },
      { position: 19, name: 'Zezinho', team: 'Tissei Motorsport' },
      { position: 20, name: 'Roger', team: 'Injetec' },
    ],
  },
  {
    areaCode: 47,
    name: 'Lista Área 47',
    format: ListFormat.TOP_20,
    administratorName: 'Ranier Sestrem',
    active: true,
    roster: [
      { position: 1, name: 'Arthur L.', car: 'GTI - White Geteco', team: 'PDL/JR Car' },
      { position: 2, name: 'Vladi', car: 'Chevette - The Crow', team: 'Pameli Competições' },
      { position: 3, name: 'Maycon', car: 'Opala V8 Blower', team: 'Top Motors' },
      { position: 4, name: 'Ranier', car: 'Gol Bege Pégasus', team: 'QuatroSete Motorsports' },
      { position: 5, name: 'Rafa', car: 'Camaro Mad Max', team: 'Rafa/Sturion' },
      { position: 6, name: 'Chiquinho 47', car: 'Gol 4x4 Sukatinha', team: 'Pork/Cunha Preparações' },
      { position: 7, name: 'Vagner 47', car: 'Gol G4 - vermelho', team: 'LL Preparações' },
      { position: 8, name: 'Silvia', car: 'Gol FLD G4 - prata', team: 'MR7 Racing' },
      { position: 9, name: 'Jé', car: 'Chevette - laranja', team: 'OHC Motors by JF' },
      { position: 10, name: 'Zanga', car: 'Gol 4x4 McQueen', team: 'QuatroSete Motorsports' },
      { position: 11, name: 'Medeiros', car: 'Golf GTI Joaninha', team: 'Medeiros Motorsport' },
      { position: 12, name: 'Buba', car: 'Chevette - azul', team: 'Helocar Centro Aut.' },
      { position: 13, name: 'By', car: 'Chevette Shark 2.0', team: 'F1 Preparações' },
      { position: 14, name: 'Diogo Tudino', car: 'Sonoma', team: 'Top Motors' },
      { position: 15, name: 'Chairom', car: 'Opala Martin Vaca', team: 'Top Motors' },
      { position: 16, name: 'Narcizo', car: 'Gol 027', team: 'AMN Performance' },
      { position: 17, name: 'Diego Liebl', car: 'Chevette 015', team: 'LL Preparações' },
      { position: 18, name: 'Divar', car: 'Gol 4x4 101', team: 'Toro Performance' },
      { position: 19, name: 'Heverton', car: 'Gol Bala de Prata', team: 'Dicar Preparações' },
      { position: 20, name: 'Jaime', car: 'Caravan 76', team: 'Fernando Preparações' },
    ],
  },
  {
    areaCode: 51,
    name: 'Lista Área 51',
    format: ListFormat.TOP_20,
    administratorName: 'Valtinho Junior',
    active: true,
    roster: [
      { position: 1, name: 'Pedro Barros', isKing: true },
      { position: 2, name: 'Pica Pau' },
      { position: 3, name: 'Talisson' },
      { position: 4, name: 'Talles' },
      { position: 5, name: 'Mark' },
      { position: 6, name: 'Maicon' },
      { position: 7, name: 'Dudu' },
      { position: 8, name: 'Sequinho' },
      { position: 9, name: 'Regis' },
      { position: 10, name: 'Jardel' },
      { position: 11, name: 'Java' },
      { position: 12, name: 'Jardel II' },
      { position: 13, name: 'Wallace' },
      { position: 14, name: 'Claudinho' },
      { position: 15, name: 'Alisson' },
      { position: 16, name: 'Márcio' },
      { position: 17, name: 'Chucky' },
      { position: 18, name: 'Chicon' },
      { position: 19, vacancy: true, name: 'Vaga 19 / Área 51' },
      { position: 20, vacancy: true, name: 'Vaga 20 / Área 51' },
    ],
  },
  {
    areaCode: 55,
    name: 'Lista Área 55',
    format: ListFormat.TOP_20,
    administratorName: 'Fabio Wisniewski',
    active: true,
    roster: [
      { position: 1, name: 'Fabio Wisniewski', isKing: true, car: 'Blue Shark (Opala SS)' },
      { position: 2, name: 'Angelo Bevilaqua', car: 'Gol' },
      { position: 3, name: 'Renan Catuípe', car: 'Gol' },
      { position: 4, name: 'Stevan Matini', car: 'Chevy' },
      { position: 5, name: 'Daniel Maia', car: 'Gol 4x4' },
      { position: 6, name: 'Ricardo N.', car: 'Gol 4x4' },
      { position: 7, name: 'Lucas Noronha', car: 'Gol 4x4' },
      { position: 8, name: 'Baessan', car: 'Gol 4x4' },
      { position: 9, name: 'Diego Godoy', car: 'Gol 4x4' },
      { position: 10, name: 'Diego DS', car: 'Fusca AR' },
      { position: 11, name: 'Lucas Mathias', car: 'Gol 4x4 Flash' },
      { position: 12, name: 'Lisoca C.', car: 'Chevette' },
      { position: 13, name: 'Thomé', car: 'Gol DTR' },
      { position: 14, name: 'Anderson 55', car: 'Saveiro' },
      { position: 15, name: 'João Vitor', car: 'Gol Diant.' },
      { position: 16, name: 'Juliano 55', car: 'Chevette' },
      { position: 17, name: 'Jader Krolow', car: 'Dodge Polara' },
      { position: 18, name: 'Jeferson Merconi', car: 'Gol 4x4' },
      { position: 19, name: 'Maicon Freitas', car: 'Chevy' },
      { position: 20, name: 'Rodrigo Perigoso', car: 'Opala' },
    ],
  },
  {
    areaCode: 65,
    name: 'Lista Área 65',
    format: ListFormat.TOP_20,
    administratorName: 'João Paulo',
    active: true,
    roster: [
      { position: 1, name: 'Eloi Bedin', car: 'Opala 888' },
      { position: 2, name: 'Paulo Moura', car: 'Opala SS' },
      { position: 3, name: 'Adriel Nantes', car: 'Gol Brutuss 4x4' },
      { position: 4, name: 'Pedro Cardozo', car: 'Amarok' },
      { position: 5, name: 'Wender Gustavo', car: 'BYD Seal' },
      { position: 6, name: 'Marcelo Bocolli', car: 'Gol Black Snake 4x4' },
      { position: 7, name: 'Felipe Ximita', car: 'Chevette' },
      { position: 8, name: 'Charles Bocolli', car: 'Gol Dark Eagle 4x4' },
      { position: 9, name: 'Jama', car: 'Gol Quadrado' },
      { position: 10, name: 'Rafael Rech', car: 'Chevette' },
      { position: 11, name: 'Diogo', car: 'Fiat Uno' },
      { position: 12, name: 'Waldez', car: 'Chevette' },
      { position: 13, name: 'Júnior Guerreiro', car: 'Dodge Charger V8 Oxido' },
      { position: 14, name: 'Hugo Bombarda', car: 'Gol 4x4' },
      { position: 15, name: 'Paulo Ricardo', car: 'Gol Frankenstein' },
      { position: 16, name: 'Dyogo Moreira', car: 'Virtus Turbo' },
      { position: 17, name: 'Eduardo Cataiau', car: 'Audi RS3' },
      { position: 18, name: 'Jorjão', car: 'Opala SS' },
      { position: 19, name: 'Cristiano', car: 'Gol Dianteira' },
      { position: 20, name: 'Marcio Knopf', car: 'Gol Sentença 4x4' },
    ],
  },
  {
    areaCode: 67,
    name: 'Lista Área 67',
    format: ListFormat.TOP_20,
    administratorName: 'Ronny Viegas',
    active: true,
    roster: [
      { position: 1, name: 'Marreco', isKing: true, car: 'Chevette', team: 'Piruka Racing' },
      { position: 2, name: 'Luis Gaucho', car: 'Gol Maragato', team: 'Valente Racing' },
      { position: 3, name: 'Glaucy Zago', car: 'Saveiro 4x4', team: 'Zago Motorsports' },
      { position: 4, name: 'Gil Geotec', car: 'Gol Geotec', team: 'Zago Motorsports' },
      { position: 5, name: 'Elder Assis', car: 'Gol Black Bull 4x4', team: 'Valente Racing' },
      { position: 6, name: 'Rodrigo Zago', car: 'Chevette', team: 'Zago Motorsports' },
      { position: 7, name: 'Robson Soler', car: 'Chevette', team: 'Valente Racing' },
      { position: 8, name: 'Rafael Tolini', car: 'Saveiro 4x4', team: 'Piruka Racing' },
      { position: 9, name: 'Márcio Cezar', car: 'Gol Pé de Pano 4x4', team: 'BM Racing' },
      { position: 10, name: 'Rodrigo C.', car: 'Gol Red Horse 4x4', team: 'Top Fuel' },
      { position: 11, name: 'Thiago Vieira', car: 'Gol', team: 'Autozone Motorsports' },
      { position: 12, name: 'Lucas 67', car: 'Gol Zé Gotinha', team: 'Piruka Racing' },
      { position: 13, name: 'Branquinho', car: 'Gol Coveiro', team: 'Branquinho Racing' },
      { position: 14, name: 'Caixote', car: 'Gol', team: 'Piruka Racing' },
      { position: 15, name: 'Tio Piruka', car: 'Gol', team: 'Piruka Racing' },
      { position: 16, name: 'André Lanteri', car: 'Chevette Azul' },
      { position: 17, name: 'Ricardo Roque', car: 'Chevette', team: 'Andracar' },
      { position: 18, name: 'Márcio Theo', car: 'Voyage' },
      { position: 19, name: 'Everaldo', car: 'Chevette' },
      { position: 20, name: 'Anderson 67', car: 'Gol 4x4' },
    ],
  },
  {
    areaCode: 95,
    name: 'Lista Área 95',
    format: ListFormat.TOP_10,
    active: true,
    roster: [
      { position: 1, name: 'Karen Rosa', car: 'Gol Snow', team: 'Belmotofort' },
      { position: 2, name: 'Neto Bitar', car: 'Gol Sherek', team: 'Garage Six In Line' },
      { position: 3, name: 'Wagner Assis', car: 'Chevette Cangaceiro', team: 'Garage Six In Line' },
      { position: 4, name: 'Gustavo Soligo', car: 'Kadett 492', team: 'Marcelo Motor Sport' },
      { position: 5, name: 'Marcos Vinicius', car: 'Gol Tomahawk', team: 'Graxa Race Motors' },
      { position: 6, name: 'Juan Martinez', car: 'Blueforin', team: 'First Automotive Solutions' },
      { position: 7, name: 'Kauã Carvalho', car: 'BMW 306', team: 'First Automotive Solutions' },
      { position: 8, name: 'Brenda Barbosa', car: 'BYD Seal', team: 'R Soluções' },
      { position: 9, name: 'Nicoletti', car: 'Audi A3', team: 'Nicoletti' },
      { position: 10, name: 'Gisley', car: 'Gol G4', team: 'Bel Motofort' },
    ],
  },
];
